### ISSUE TITLE
Training on Custom Dataset?? 

### ISSUE THREAD

**Issue by MohammadVahidiPro** [studio-ousia/ease#9]
Greetings! I am writing to express my keen interest in your work and to request advice on training with a custom dataset. Particularly, I don't know how to build the entity files for my dataset to run the training. Could you please tell me what I should change to achieve this? I would greatly appreciate your guidance. Thank you for your immense contributions to the community.

**Comment by MohammadVahidiPro** [comment]
Has anyone trained this model on custom data? I would appreciate your help.

**Comment by Sosuke115** [comment]
Please refer to [this code](https://github.com/studio-ousia/ease/tree/main/build_dataset). 
You can download the raw unprocessed data from [this link](https://dumps.wikimedia.org/wikidatawiki/entities/).

**Comment by MohammadVahidiPro** [comment]
Thank you very much for your help, I had another problem I would be grateful I you could assist me.
While running this line in the "main.py" file, I encountered "Not enough memory error" in my laptop, therefore, I am wondering if there is a way around the memory issues? Are there any alternative ways to load embeddings from "data/enwiki.fp16.768.vec"? 
Thanks in advance.

Code:
```python
# main.py line:213
# load pretrained entity embeddings (file: "data/enwiki.fp16.768.vec")
embedding = Wikipedia2Vec.load(os.path.join(cwd, data_args.wikipedia2vec_path))
``` 

Error:
<details><summary>Details</summary>
<p>
Traceback (most recent call last):
  File "wiki_process.py", line 60, in <module>
    embedding = Wikipedia2Vec.load(os.path.join(cwd, wikipedia2vec_path))
  File "wikipedia2vec/wikipedia2vec.pyx", line 172, in wikipedia2vec.wikipedia2vec.Wikipedia2Vec.load
    obj = joblib.load(in_file, mmap_mode=numpy_mmap_mode)
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\98914\anaconda3\envs\wick\lib\pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\joblib\numpy_pickle.py", line 344, in load_build
    self.stack.append(array_wrapper.read(self))
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\joblib\numpy_pickle.py", line 187, in read
    array = self.read_mmap(unpickler)
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\joblib\numpy_pickle.py", line 165, in read_mmap
    offset=offset)
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\joblib\backports.py", line 35, in make_memmap
    shape=shape, order=order)
  File "C:\Users\98914\anaconda3\envs\wick\lib\site-packages\numpy\core\memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [WinError 8] Not enough memory resources are available to process this command

</p>


</details>

**Comment by Sosuke115** [comment]
@MohammadVahidiPro 
According to the error log, it appears to be an out-of-memory error.

**Comment by Sosuke115** [comment]
@MohammadVahidiPro 
By reducing the vocabulary size of the vector, you might be able to avoid out-of-memory error. 
(However, this might result in a decrease in the performance of "ease".)

**Comment by MohammadVahidiPro** [comment]
thanks a lot, I'll try it.
